// -------------------------------------------------- //
// This file is auto-generated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"

// ----------- //
// ili9341_spi //
// ----------- //

#define ili9341_spi_wrap_target 0
#define ili9341_spi_wrap 1

static const uint16_t ili9341_spi_program_instructions[] = {
            //     .wrap_target
    0x6101, //  0: out    pins, 1         side 0 [1] 
    0x0100, //  1: jmp    0               side 1 [1] 
            //     .wrap
};

#if !PICO_NO_PIOASM
static const struct pio_program ili9341_spi_program = {
    .instructions = ili9341_spi_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config ili9341_spi_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + ili9341_spi_wrap_target, offset + ili9341_spi_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void ili9341_spi_program_init(PIO pio, uint sm, uint offset, uint mosi_pin, uint clk_pin, float div) {
    pio_gpio_init(pio, mosi_pin);
    pio_gpio_init(pio, clk_pin);
    pio_sm_set_consecutive_pindirs(pio, sm, mosi_pin, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, clk_pin, 1, true);

    pio_sm_config c = ili9341_spi_program_get_default_config(offset);
    sm_config_set_out_pins(&c, mosi_pin, 1);
    sm_config_set_sideset_pins(&c, clk_pin);
    
    // MSB first, autopull enabled, threshold 16 bits (RGB565)
    sm_config_set_out_shift(&c, false, true, 16); 
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    sm_config_set_clkdiv(&c, div);

    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
}
#endif

#endif
